CREATE TABLE `Gallery` (
  `Id` char(16) PRIMARY KEY NOT NULL,
  `Description` varchar(4000) DEFAULT NULL,
  `Url` varchar(1000) DEFAULT NULL,
  `Style` int DEFAULT NULL,
  `CreateDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8
